image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DEPLOYMENT_DIR: "distr"

ng-build:
  image: node:11
  stage: build
  script: 
    - "npm install -g @angular/cli@7.0.4"
    - "ls -ltr"
  artifacts:
    paths:
      - $DEPLOYMENT_DIR
    expire_in: 1 hour
