image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DEPLOYMENT_DIR: "dist"

ng-build:
  image: node:11
  stage: build
  script: 
    - "npm install -g @angular/cli@7.0.4"
    - "rm ./package-lock.json"
    - "npm install"
    - "ng build --prod --aot"
  artifacts:
    paths:
      - $DEPLOYMENT_DIR
    expire_in: 1 hour

aws-deploy:
  image: python
  stage: deploy
  script:
    - "pip3 install awscli --upgrade"
    - "aws --version"
    - "aws s3 rm s3://$AWS_S3_BUCKET/"
    - "aws s3 cp $DEPLOYMENT_DIR s3://$AWS_S3_BUCKET/"